services:
  agent:
    build:
      context: ./multiagent
      dockerfile: Dockerfile
    container_name: orchestrator_agent
    networks:
      - oraculo-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    ports:
      - "8004:8004"
    stdin_open: true
    tty: true

  edite_agent:
    build:
      context: ./edite_agent
      dockerfile: Dockerfile
    container_name: edite_agent
    image: edite_agent:latest
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "8003:8003"
    env_file:
      - .env
    networks:
      - oraculo-network

networks:
  oraculo-network:
    name: oraculo-network
    external: true
